### ISSUE TITLE
[rumqttc] - Using websocket feature makes EventLoop not Send / can't be spawned with tokio::spawn

### ISSUE THREAD

**Issue by brocaar** [bytebeamio/rumqtt#807]
# Expected Behavior

First of all thanks for your work on this project :+1: 

I'm using your `rumqttc` library as follow:

* I setup the v5 `AsyncClient` which returns the client + eventloop (`let (client, mut eventloop) = AsyncClient::new(mqtt_opts, 100);`
* I use `tokio::spawn` to then handle the eventloop

This worked fine until I tried to enable the `websocket` feature.

# Current Behavior

After enabling the `websocket` feature this no longer works, I get the following error:

```
error: future cannot be sent between threads safely
   --> src/mqtt.rs:194:18
    |
194 |       tokio::spawn({
    |  __________________^
195 | |         async move {
196 | |             info!("Starting MQTT event loop");
197 | |
...   |
228 | |         }
229 | |     });
    | |_____^ future created by async block is not `Send`
    |
    = help: the trait `Send` is not implemented for `(dyn Fn(http::request::Request<()>) -> Pin<Box<(dyn Future<Output = http::request::Request<()>> + 'static)>> + 'static)`
note: captured value is not `Send`
   --> src/mqtt.rs:199:23
    |
199 |                 match eventloop.poll().await {
    |                       ^^^^^^^^^ has type `rumqttc::v5::EventLoop` which is not `Send`
note: required by a bound in `tokio::spawn`
```

* Is this expected behavior?
* What would be the intended way to handle such case (I think it is pretty common to handle the evenloop in the background)?

**Comment by brocaar** [comment]
Looking at the source, I think this is a duplicate of https://github.com/bytebeamio/rumqtt/issues/769 and this was already fixed. I will do some testing against this change.

If that is the case, would you mind creating a new release?

**Comment by swanandx** [comment]
>  I will do some testing against this change.
>
cool, try out rumqttc from main branch, as mentioned, this should be fixed.

> would you mind creating a new release?
>
on it!

**Comment by swanandx** [comment]
rumqttc v0.24.0 is released :rocket: thanks you!

**Comment by Leandros** [comment]
This isn't fixed. The `EventLoop` type is still `!Sync`, which is required for it to be send across threads (and, more importantly, to spawn it).

How do people even use this library without the eventloop being spawnable?

**Comment by swanandx** [comment]
> This isn't fixed. The `EventLoop` type is still `!Sync`, which is required for it to be send across threads (and, more importantly, to spawn it).
> 
> How do people even use this library without the eventloop being spawnable? 

can you please explain the exact issue you are facing and if possible give a minimal poc as well?

**Comment by Leandros** [comment]
The `EventLoop` type isn't `Sync`. This is due to it containing an `Option<Network>` member, which has `socket: Box<dyn N>`, that isn't `Sync`.

Trying to share the `EventLoop` by wrapping it with an `RwLock` will result in an error.

This is a small reproducible example showing the issue:

<details>
<summary>Example</summary>

```rust
use rumqttc::{AsyncClient, EventLoop, MqttOptions, QoS};
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::RwLock;
use tokio::time;

struct Inner {
    client: AsyncClient,
    eventloop: RwLock<EventLoop>,
}

struct Context {
    inner: Arc<Inner>,
}

impl Context {
    fn new() -> Self {
        let mut mqttoptions = MqttOptions::new("rumqtt-async", "test.mosquitto.org", 1883);
        mqttoptions.set_keep_alive(Duration::from_secs(5));

        let (client, eventloop) = AsyncClient::new(mqttoptions, 10);

        Self {
            inner: Arc::new(Inner {
                client,
                eventloop: RwLock::new(eventloop),
            }),
        }
    }

    async fn subscribe(&self) {
        self.inner
            .client
            .subscribe("hello/rumqtt", QoS::AtMostOnce)
            .await
            .unwrap();
    }

    fn startloop(&self) {
        let inner = Arc::clone(&self.inner);
        // rustc: future cannot be sent between threads safely
        // the trait `std::marker::Sync` is not implemented for `(dyn rumqttc::framed::N + 'static)`, which is required by `{async block@src/main.rs:41:22: 41:32}: std::marker::Send`
        tokio::spawn(async move { // <-- throws aboves error
            let mut lock = inner.eventloop.write().await; // <-- captured value is net `Send`
            while let Ok(notification) = lock.poll().await {
                println!("Received = {:?}", notification);
            }
        });
    }
}

#[tokio::main]
async fn main() {
    let context = Context::new();
    context.subscribe().await;
    context.startloop();

    for i in 0..10 {
        context
            .inner
            .client
            .publish("hello/rumqtt", QoS::AtLeastOnce, false, vec![i; i as usize])
            .await
            .unwrap();
        time::sleep(Duration::from_secs(1)).await;
    }
}
```
</details>

This is mitigated by instead wrapping it in a `Mutex`, making it `Sync`.

This might actually be a non-issue.
